name: Test formula

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - name: Check tap syntax
        run: brew test-bot --only-tap-syntax
      - name: Build and test formula
        run: brew test-bot --only-formulae
